(async()=>{
 try{
  const [d,dict]=await Promise.all([loadAll(),getI18n()]);
  const lang=getLang(d.languages.enabled);document.documentElement.lang=lang;applyAppearance(d.appearance||{});applyI18n(dict,lang);renderHeader(d.site,dict,d.languages.enabled);
  const path=location.pathname.split('/').pop()||'index.html';
  if(path==='index.html'||path==='')renderHome(d,dict,lang); else if(path==='research.html')renderResearchPage(d,dict,lang); else if(path==='research-detail.html')renderResearchDetail(d,dict,lang); else if(path==='publications.html')renderPublicationsPage(d,dict,lang); else if(path==='experience.html')renderExperiencePage(d,dict,lang); else if(path==='skills.html')renderSkillsPage(d,dict,lang); else if(path==='skill-detail.html')renderSkillDetail(d,dict,lang); else if(path==='settings.html'){const f=document.querySelector('#footer');if(f)f.innerHTML=`<div class="container footer-inner"><div><strong>${esc(d.site.name)}</strong><div>Plant Science • Research • Biotechnology</div></div><div>© ${new Date().getFullYear()} ${esc(d.site.name)}. All rights reserved.</div></div>`;}
 }catch(e){console.error(e);document.body.insertAdjacentHTML('beforeend',`<div style="padding:2rem;color:#900">Portfolio could not load. Please check the repository file paths.</div>`)}
})();

function applyAppearance(a){
 const root=document.documentElement, c=a.colors||{};
 const map={primary:'--primary',secondary:'--gold',accent:'--gold2',background:'--cream',surface:'--surface',text:'--ink',textSecondary:'--muted',darkBackground:'--dark',darkSurface:'--dark2',darkText:'--white'};
 Object.entries(map).forEach(([k,v])=>{if(c[k])root.style.setProperty(v,c[k])});
 if(a.cardRadius)root.style.setProperty('--radius',a.cardRadius+'px');
 if(a.headingWeight)root.style.setProperty('--heading-weight',String(a.headingWeight));
 if(a.letterSpacing)root.style.setProperty('--letter-spacing',a.letterSpacing);
 if(a.lineHeight)root.style.setProperty('--line-height',a.lineHeight);
 if(a.contentMaxWidth)root.style.setProperty('--content-max',a.contentMaxWidth);
 if(a.buttonRadius)root.style.setProperty('--button-radius',a.buttonRadius+'px');
 if(a.sectionSpacing)root.style.setProperty('--section-spacing',a.sectionSpacing);
 if(a.shadowStrength!==undefined)root.style.setProperty('--shadow-strength',String(a.shadowStrength));
 if(a.font)root.style.setProperty('--font',a.font==='Georgia'?'Georgia,"Times New Roman",serif':a.font==='System'?'system-ui,-apple-system,"Segoe UI",sans-serif':'Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif');
 const bg=a.backgroundImage||"assets/images/scientific-background.png";
 let bgUrl=''; try{bgUrl=new URL(bg.replace(/^\/+/,''),document.baseURI).href}catch{}
 root.style.setProperty('--scientific-bg',bgUrl?`url("${bgUrl}")`:`url("assets/images/scientific-background.png")`);
 root.style.setProperty('--scientific-fit',a.backgroundFit||'cover');
 root.style.setProperty('--scientific-position',a.backgroundPosition||'center');
 const sectionEnabled=a.sectionBackgroundEnabled!==false;
 const op=sectionEnabled?Math.max(0,Math.min(1,Number(a.backgroundOpacity??.18))):0;
 root.style.setProperty('--scientific-opacity',op);
 root.style.setProperty('--scientific-global-opacity',sectionEnabled?Math.max(.18,Math.min(.42,op*1.8)):0);
 root.style.setProperty('--scientific-light-opacity',Math.min(.28,Math.max(.12,op*1.15)));
 root.style.setProperty('--scientific-dark-opacity',Math.min(.30,Math.max(.14,op*1.05)));
 root.style.setProperty('--scientific-overlay',`linear-gradient(${a.gradientAngle||'135deg'}, ${a.gradientStart||'#0A0A0B'}, ${a.gradientEnd||'#1A1407'})`);
  root.style.setProperty('--scientific-page-size',a.backgroundScale||a.backgroundSize||a.backgroundFit||'cover');
  root.style.setProperty('--scientific-mobile-size',a.backgroundMobileScale||a.backgroundScale||a.backgroundSize||'cover');
  root.style.setProperty('--scientific-attachment',a.backgroundAttachment||'fixed');
  root.style.setProperty('--scientific-repeat',a.backgroundRepeat||'no-repeat');
  root.style.setProperty('--scientific-page-overlay',String(Math.max(0,Math.min(1,Number(a.backgroundOverlayOpacity??.34)))));
  root.style.setProperty('--scientific-gradient-angle',a.gradientAngle||'135deg');
  root.style.setProperty('--scientific-gradient-start',a.gradientStart||'rgba(10,10,11,.78)');
  root.style.setProperty('--scientific-gradient-end',a.gradientEnd||'rgba(26,20,7,.68)');
  root.style.setProperty('--button-bg',a.buttonBackground||'#E9C46A');root.style.setProperty('--button-text',a.buttonText||'#14100A');root.style.setProperty('--button-border',a.buttonBorder||'#C9A227');
}

function renderHome(d,dict,lang){
 const s=d.site,a=d.about;
 document.title=`${s.name} — Plant Science Researcher`;
 const hero=document.querySelector('#hero');if(hero){hero.innerHTML=`<div class="container hero-grid"><div><div class="eyebrow">${esc(s.heroLabel)}</div><h1>${esc(s.name||'Fahad Badsha Shamim')}</h1><div class="hero-tagline">${esc(s.professionalTitle)} | ${esc(s.heroTagline)}</div><p class="hero-desc">${esc(s.heroDescription)}</p>${s.showButtons!==false?`<div class="actions"><a class="btn btn-primary" href="${esc(s.primaryButtonLink||'research.html')}">${esc(s.primaryButtonText||'View Research')}</a>${s.cvUrl||s.secondaryButtonLink?`<a class="btn btn-outline" href="${esc(s.cvUrl||s.secondaryButtonLink)}" target="_blank" rel="noopener noreferrer">${esc(s.secondaryButtonText||'Download CV')}</a>`:''}</div>`:''}<div class="hero-social" id="heroSocial"></div></div><div class="portrait-wrap"><div class="portrait"><img src="${esc(safeImage(s.heroImage))}" alt="${esc(s.name)}" loading="eager"></div><div class="hero-badge">MSc Plant Science • Bonn, Germany</div></div></div>`;renderSocial(document.getElementById('heroSocial'),s,d.contact)}
 const about=document.querySelector('#about');if(about){about.innerHTML=`<div class="container about-grid"><div><div class="about-photo"><img src="${esc(safeImage(a.profileImage))}" alt="${esc(s.name)}" loading="lazy"></div></div><div><div class="eyebrow">WHO I AM</div><h2 class="section-heading" data-i18n="aboutTitle">${esc(a.heading||'About Me')}</h2><div class="rule"></div><p class="about-body">${esc(a.biography)}</p><div class="info-grid">${(a.cards||[]).map(c=>`<div class="info-card"><div class="label">${esc(c.label)}</div><div class="value">${esc(c.value)}</div></div>`).join('')}</div></div></div>`}
 const rg=document.querySelector('#researchPreview');if(rg){const list=[...(d.research||[])].sort((x,y)=>(x.order??0)-(y.order??0)).slice(0,3);rg.innerHTML=`<div class="container"><div class="eyebrow">SELECTED WORK</div><h2 class="section-heading" data-i18n="navResearch">Research</h2><div class="rule"></div><div class="research-grid">${list.map(researchCard).join('')}</div><div style="text-align:center;margin-top:2rem"><a class="btn btn-primary" href="research.html">View all research →</a></div></div>`}
 const pg=document.querySelector('#publicationsPreview');if(pg){const pubs=(d.publications||[]).slice(0,3);pg.innerHTML=`<div class="container"><div class="eyebrow">PEER-REVIEWED WORK</div><h2 class="section-heading" data-i18n="navPublications">Selected Publications</h2><div class="rule"></div><div class="publication-grid">${pubs.map(publicationCard).join('')}</div><div style="text-align:center;margin-top:2rem"><a class="btn btn-outline-dark" href="publications.html">View all publications →</a></div></div>`}
 const ex=document.querySelector('#experience');if(ex){const items=d.experience||[];ex.innerHTML=`<div class="container"><div class="eyebrow">PROFESSIONAL PATH</div><h2 class="section-heading" data-i18n="navExperience">Experience</h2><div class="rule"></div><div class="experience-grid">${items.map(e=>`<article class="experience-card"><div class="meta"><span>${esc(e.organization)}</span><span>${esc([e.startDate,e.endDate].filter(Boolean).join(' – '))}</span></div><h3>${esc(e.role)}</h3><p>${esc(e.description)}</p><div class="experience-location">${esc(e.location)}</div></article>`).join('')}</div></div>`}
 const sg=document.querySelector('#skills');if(sg){sg.innerHTML=`<div class="container"><div class="eyebrow">CAPABILITIES</div><h2 class="section-heading" data-i18n="skillsTitle">Skills</h2><div class="rule"></div><div class="skills-grid">${(d.skills||[]).map(c=>`<div class="skill-category"><h3>${esc(c.category)}</h3><div class="pills">${(c.skills||[]).map(x=>`<a class="pill" href="skill-detail.html?skill=${encodeURIComponent(x)}">${esc(x)}</a>`).join('')}</div></div>`).join('')}</div><div style="margin-top:2rem"><a class="link-arrow" href="skills.html">Explore skill details →</a></div></div>`}
 const ed=document.querySelector('#education');if(ed){ed.innerHTML=`<div class="container"><div class="eyebrow">ACADEMIC PATH</div><h2 class="section-heading" data-i18n="educationTitle">Education</h2><div class="rule"></div><div class="timeline">${(d.education||[]).map(e=>`<div class="timeline-item"><div class="timeline-dot"></div><div class="edu-card"><div class="degree">${esc(e.degree)} ${e.current?'<span class="current-badge">Current</span>':''}</div><div class="inst">${esc([e.institution,e.location].filter(Boolean).join(', '))}</div><div class="period">${esc([e.startDate,e.current?'Present':e.endDate].filter(Boolean).join(' – '))}</div>${e.description?`<p>${esc(e.description)}</p>`:''}</div></div>`).join('')}</div></div>`}
 const c=document.querySelector('#contact');if(c){const links=[['Email',d.contact.email?'mailto:'+d.contact.email:''],['LinkedIn',d.contact.linkedin],['GitHub',d.contact.github],['ResearchGate',d.contact.researchgate],['ORCID',d.contact.orcid]].filter(x=>x[1]);c.innerHTML=`<div class="container contact-grid"><div><div class="eyebrow">GET IN TOUCH</div><h2 class="section-heading" data-i18n="contactTitle">Contact</h2><div class="rule"></div><p>${esc(d.contact.intro)}</p></div><div class="contact-card"><div class="contact-list">${links.map(([l,u])=>`<a class="contact-item" href="${esc(safeUrl(u))}" ${u.startsWith('http')?'target="_blank" rel="noopener noreferrer"':''}><strong>${esc(l)}</strong><span>${esc(u.replace(/^mailto:/,''))}</span></a>`).join('')}</div></div></div>`}
 const cs=document.querySelector('#customSections');if(cs){const items=[...(d['custom-sections']||[])].filter(x=>x.visible!==false).sort((a,b)=>(a.order??0)-(b.order??0));cs.innerHTML=items.map(customSectionHtml).join('')}
 const foot=document.querySelector('#footer');if(foot)foot.innerHTML=`<div class="container footer-inner"><div><strong>${esc(s.name)}</strong><div>Plant Science • Research • Biotechnology</div></div><div>© ${new Date().getFullYear()} ${esc(s.name)}. All rights reserved.</div></div>`;
}
function customSectionHtml(x){const theme=x.theme==='dark'?'dark':'light';const img=x.image?`<div class="custom-section-media"><img src="${esc(safeImage(x.image))}" alt="" loading="lazy"></div>`:'';return `<section class="section ${theme} custom-section"><div class="container custom-section-grid">${img}<div><div class="eyebrow">${esc(x.eyebrow||'ADDITIONAL')}</div><h2 class="section-heading">${esc(x.title||'Section')}</h2><div class="rule"></div><div class="custom-section-body">${esc(x.body||'').replace(/\n/g,'<br>')}</div></div></div></section>`}
function researchCard(r){return `<article class="research-card"><div class="research-thumb">${r.image?`<img src="${esc(safeImage(r.image))}" alt="${esc(r.title)}" loading="lazy">`:''}</div><div class="research-body"><div class="meta"><span>${esc(r.category)}</span><span>${esc(r.year)}</span></div><h3>${esc(r.title)}</h3><p>${esc(r.description)}</p><div class="tags">${(r.tags||[]).slice(0,4).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><a class="link-arrow" href="research-detail.html?slug=${encodeURIComponent(r.slug)}">View project →</a></div></article>`}
function renderResearchPage(d,dict,lang){const main=document.querySelector('#page');const list=[...(d.research||[])].sort((a,b)=>(a.order??0)-(b.order??0));main.innerHTML=`<section class="detail-hero scientific-bg"><div class="container"><div class="eyebrow">RESEARCH PORTFOLIO</div><h1>Research Projects</h1><p style="max-width:680px;color:#c9c4b8">A structured overview of research projects, methods, findings and publication resources.</p></div></section><section class="section light"><div class="container"><div class="research-grid">${list.length?list.map(researchCard).join(''):`<div class="empty">${dict[lang].noProjects}</div>`}</div></div></section>`}
function renderResearchDetail(d,dict,lang){const slug=new URLSearchParams(location.search).get('slug');const r=(d.research||[]).find(x=>x.slug===slug)||null;const main=document.querySelector('#page');if(!r){main.innerHTML=`<section class="section light"><div class="container"><div class="empty">${dict[lang].notFound}</div></div></section>`;return}document.title=`${r.title} — ${d.site.name}`;main.innerHTML=`<section class="detail-hero scientific-bg"><div class="container"><div class="eyebrow">${esc(r.category)} • ${esc(r.year)}</div><h1>${esc(r.title)}</h1></div></section><section class="section light"><div class="container detail-layout"><article class="detail-main"><h2>${dict[lang].details}</h2><p>${esc(r.description)}</p><h2>${dict[lang].methods}</h2><p>${esc(r.methods)}</p><h2>Key results</h2><ul class="result-list">${(r.results||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h2>${dict[lang].tags}</h2><div class="tags">${(r.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></article><aside class="detail-side"><strong>${esc(r.publication?.journal||'Publication')}</strong><p>${esc([r.publication?.volume,r.publication?.pages,r.publication?.year].filter(Boolean).join(' • '))}</p>${r.publication?.doi?`<p><strong>DOI</strong><br>${esc(r.publication.doi)}</p>`:''}${r.externalUrl?`<a href="${esc(safeUrl(r.externalUrl))}" target="_blank" rel="noopener noreferrer">${dict[lang].publication} ↗</a>`:''}${r.pdfUrl?`<a href="${esc(safeUrl(r.pdfUrl))}" target="_blank" rel="noopener noreferrer">${dict[lang].pdf} ↗</a>`:''}${r.githubUrl?`<a href="${esc(safeUrl(r.githubUrl))}" target="_blank" rel="noopener noreferrer">${dict[lang].github} ↗</a>`:''}<a href="research.html">← ${dict[lang].back}</a></aside></div></section>`}
function publicationCard(p){return `<article class="publication-card"><div class="publication-year">${esc(p.year)}</div><h3>${esc(p.title)}</h3><p class="publication-venue">${esc(p.venue)}</p><p class="publication-authors">${esc(p.authors)}</p>${p.doi?`<p class="doi">DOI: ${esc(p.doi)}</p>`:''}<div class="publication-actions">${p.externalUrl?`<a class="link-arrow" href="${esc(safeUrl(p.externalUrl))}" target="_blank" rel="noopener noreferrer">${'Publication'} ↗</a>`:''}${p.pdfUrl?`<a class="link-arrow" href="${esc(safeUrl(p.pdfUrl))}" target="_blank" rel="noopener noreferrer">PDF ↗</a>`:''}${p.projectSlug?`<a class="link-arrow" href="research-detail.html?slug=${encodeURIComponent(p.projectSlug)}">Project ↗</a>`:''}</div></article>`}
function renderPublicationsPage(d,dict,lang){const main=document.querySelector('#page');main.innerHTML=`<section class="detail-hero scientific-bg"><div class="container"><div class="eyebrow">PEER-REVIEWED WORK</div><h1>${dict[lang].navPublications||'Publications'}</h1><p style="max-width:760px;color:#c9c4b8">Selected research publications with authentic journal, DOI and full-text resources where available.</p></div></section><section class="section light"><div class="container"><div class="publication-grid publication-grid-page">${(d.publications||[]).map(publicationCard).join('')}</div></div></section>`}
function renderExperiencePage(d,dict,lang){const main=document.querySelector('#page');main.innerHTML=`<section class="detail-hero scientific-bg"><div class="container"><div class="eyebrow">PROFESSIONAL PATH</div><h1>${dict[lang].navExperience||'Experience'}</h1><p style="max-width:760px;color:#c9c4b8">Teaching, web-development and youth-leadership experience supporting a multidisciplinary academic profile.</p></div></section><section class="section light"><div class="container"><div class="experience-grid">${(d.experience||[]).map(e=>`<article class="experience-card"><div class="meta"><span>${esc(e.organization)}</span><span>${esc([e.startDate,e.endDate].filter(Boolean).join(' – '))}</span></div><h2>${esc(e.role)}</h2><p>${esc(e.description)}</p><div class="experience-location">${esc(e.location)}</div></article>`).join('')}</div></div></section>`}
function renderSkillsPage(d,dict,lang){const main=document.querySelector('#page');main.innerHTML=`<section class="detail-hero scientific-bg"><div class="container"><div class="eyebrow">CAPABILITIES</div><h1>${dict[lang].skillsTitle}</h1><p style="max-width:680px;color:#c9c4b8">Each skill is a dedicated page so methods, evidence, software and future development can be documented without overcrowding the main portfolio.</p></div></section><section class="section light"><div class="container"><div class="skills-grid">${(d.skills||[]).map(c=>`<div class="skill-category" style="border-top:1px solid #e8e2d5"><h3 style="color:#80640f">${esc(c.category)}</h3><div class="pills">${(c.skills||[]).map(s=>`<a class="pill" style="color:#5b4a19;border-color:#d9c98d;background:#fff" href="skill-detail.html?skill=${encodeURIComponent(s)}">${esc(s)} ↗</a>`).join('')}</div></div>`).join('')}</div></div></section>`}
function renderSkillDetail(d,dict,lang){const name=new URLSearchParams(location.search).get('skill');const s=(d['skill-details']||[]).find(x=>x.name===name);const main=document.querySelector('#page');if(!s){main.innerHTML=`<section class="section light"><div class="container"><div class="empty">${dict[lang].notFound}</div></div></section>`;return}document.title=`${s.name} — ${d.site.name}`;main.innerHTML=`<section class="detail-hero scientific-bg"><div class="container"><div class="eyebrow">${esc(s.category)}</div><h1>${esc(s.name)}</h1><p style="max-width:700px;color:#c9c4b8">${esc(s.summary)}</p></div></section><section class="section light"><div class="container skill-detail-grid"><article class="skill-detail-card"><h2>${esc(s.name)}</h2><p>${esc(s.details)}</p><h3>Evidence & examples</h3>${s.evidence?.length?`<ul>${s.evidence.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:`<div class="empty">Add evidence, methods, coursework, projects or links for this skill from the dashboard.</div>`}</article><aside class="detail-side"><a href="skills.html">← ${dict[lang].back}</a><a href="research.html">Research projects →</a></aside></div></section>`}
